services:
  postgresql:
    image: postgres:16
    ports:
      - "5050:5432"
    environment:
      POSTGRES_DB: translator
      POSTGRES_USER: weuizx
      POSTGRES_PASSWORD: weuizx
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/translator
      - --username=weuizx
      - --password=weuizx
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend


volumes:
  postgresql: { }

networks:
  backend: { }
